'use client';
import './globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Image from 'next/image';
import logo from './app-logo.png';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-slate-700 h-screen shadow-inner">
        <nav className="bg-slate-300">
          <Link href="/">
            <Image src={logo} width={"100"} height={"25"} alt='app-logo'></Image>
          </Link>
        </nav>
        <div id='main'>
        {children}
        </div>
      </body>
    </html>
  );
}
